# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomes', models.DateField()),
                ('qt_publicacoes', models.IntegerField()),
                ('qt_videos', models.IntegerField()),
                ('qt_horas', models.IntegerField()),
                ('qt_revisitas', models.IntegerField()),
                ('qt_estudos', models.IntegerField()),
                ('priv_mes', models.CharField(choices=[('', ''), ('30', 'Pioneiro Auxiliar 30H'), ('50', 'Pioneiro Auxiliar 50h')], default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Congregacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('reuniao_meio', models.DateField()),
                ('reuniao_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(blank=True, max_length=15, null=True)),
                ('cidade', models.CharField(blank=True, default='Viam\xe3o', max_length=50, null=True)),
                ('estado', models.CharField(choices=[('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SP', 'S\xe3o Paulo')], default='RS', max_length=2)),
                ('pais', models.CharField(blank=True, default='Brasil', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('reuniao_meio', models.DateField()),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Enderecos')),
            ],
        ),
        migrations.CreateModel(
            name='Publicadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('rg', models.CharField(blank=True, max_length=11, null=True)),
                ('dt_nasc', models.CharField(blank=True, max_length=10, null=True)),
                ('dt_batismo', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('priv_congregacao', models.CharField(choices=[('anciao_cc', 'Anci\xe3o - coordenador'), ('anciao_se', 'Anci\xe3o - secret\xe1rio'), ('anciao_ss', 'Anci\xe3o - superintendente de servi\xe7o'), ('anciao', 'Anci\xe3o'), ('servo', 'Servo ministerial')], max_length=10)),
                ('priv_ministerio', models.CharField(choices=[('PB', 'Publicador'), ('PR', 'Pioneiro Regular')], max_length=2)),
                ('congregacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Congregacao')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Enderecos')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Grupos')),
            ],
        ),
        migrations.AddField(
            model_name='congregacao',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Enderecos'),
        ),
        migrations.AddField(
            model_name='atividades',
            name='id_pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Publicadores'),
        ),
    ]
