# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregacao',
            name='reuniao_fim',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='congregacao',
            name='reuniao_meio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
