# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_remove_grupos_reuniao_meio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='anomes',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
