# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_auto_20171023_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='anomes',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
